// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdQhi6Oo5K4rNms57KfPn63lij7bm5AFQ',
    appId: '1:9318667705:web:c4e219f4561647448fd268',
    messagingSenderId: '9318667705',
    projectId: 'medistock-51865',
    authDomain: 'medistock-51865.firebaseapp.com',
    storageBucket: 'medistock-51865.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQhi6Oo5K4rNms57KfPn63lij7bm5AFQ',
    appId: '1:9318667705:android:c4e219f4561647448fd268',
    messagingSenderId: '9318667705',
    projectId: 'medistock-51865',
    storageBucket: 'medistock-51865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdQhi6Oo5K4rNms57KfPn63lij7bm5AFQ',
    appId: '1:9318667705:ios:c4e219f4561647448fd268',
    messagingSenderId: '9318667705',
    projectId: 'medistock-51865',
    storageBucket: 'medistock-51865.firebasestorage.app',
    iosBundleId: 'com.example.medistockFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdQhi6Oo5K4rNms57KfPn63lij7bm5AFQ',
    appId: '1:9318667705:macos:c4e219f4561647448fd268',
    messagingSenderId: '9318667705',
    projectId: 'medistock-51865',
    storageBucket: 'medistock-51865.firebasestorage.app',
    iosBundleId: 'com.example.medistockFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdQhi6Oo5K4rNms57KfPn63lij7bm5AFQ',
    appId: '1:9318667705:windows:c4e219f4561647448fd268',
    messagingSenderId: '9318667705',
    projectId: 'medistock-51865',
    storageBucket: 'medistock-51865.firebasestorage.app',
  );
}
